[kroma]
type = "nixos"
system = "x86_64-linux"

[nom]
type = "nixos"
system = "x86_64-linux"

[sentinel]
type = "nixos"
system = "x86_64-linux"

[ward]
type = "nixos"
system = "x86_64-linux"

[sire]
type = "nixos"
system = "x86_64-linux"

[zackbiene]
type = "nixos"
system = "aarch64-linux"
